#!/bin/bash
####################################
#
# Backup to NFS mount script.
#
####################################

# PATH FROM. 
backup_files="/home/spec/backup_source"

# PATH TO
dest="/mnt/backup_source"

# Create archive filename.
day=$(date +%A)
hostname=$(hostname -s)
archive_file="$hostname-$day.tgz"

# Print status.
echo "Backing up $backup_files to $dest/$archive_file"
date
echo

#  using tar.
tar czf $dest/$archive_file $backup_files

# Print status.
echo
echo "Backup finished"
date

# Long listing of files in $dest to check file sizes.
ls -lh $dest

#REMEMBER file must be made executable:
sudo chmod u+x /home/our_script.sh
#TRY like working our script 
sudo ./our_script.sh

#add script in crontab
sudo crontab -e 

#edit file crontab m h dom mon dow   command
0 0 * * * bash /home/our_script.sh
